"""
TernaryGuard — Ternary Linear Layer & Supporting Modules

Implements the core building blocks for a 1.58-bit (ternary) neural network:

    TernaryLinear   — Drop-in replacement for nn.Linear with ternary weight
                      quantization ({-1, 0, +1}) via absmean thresholding and
                      Straight-Through Estimator (STE) for gradient flow.

    RMSNorm         — Root Mean Square normalization for activation scaling,
                      used before each TernaryLinear layer.

    TernaryMLP      — Complete multi-layer perceptron wired with the above,
                      sized for IoT intrusion detection under extreme memory
                      constraints (target: 2KB RAM / 32KB flash on ATmega328P).

Quantization method (BitNet b1.58 style):
    scale     = mean(|W|)                    # absmean scaling factor
    threshold = 0.5 * scale
    W_q[i,j]  = +1  if W[i,j] >  threshold
                -1  if W[i,j] < -threshold
                 0  otherwise

    y = (W_q @ x) * scale + bias

    Since W_q ∈ {-1, 0, +1}, the matrix-vector product reduces to:
        y_j = scale * ( Σ x_i [w=+1]  -  Σ x_i [w=-1] )
    No multiplication is needed in the inner loop — only add, subtract, skip.

2-bit packed encoding (CANONICAL — used by all engines):
    Each ternary weight is stored as 2 bits, 4 trits per byte, LSB-first:
        0b00 = 0   (skip)
        0b01 = +1  (add)
        0b10 = -1  (subtract)
        0b11 = unused / reserved

    Byte layout: [trit3:trit2:trit1:trit0] where trit0 occupies bits [1:0].

    This encoding is shared across:
        - model_weights.h   (C header, generated by export_weights_header())
        - engine-arduino/   (Phase 5 C inference, decodes with & 0x03 mask)
        - engine-fpga/      (Phase 6 Verilog, decodes with 2-bit slice)

    Any change to this mapping MUST be propagated to all three consumers.

References:
    [1] Ma et al., "The Era of 1-bit LLMs: All Large Language Models are
        in 1.58 Bits", arXiv:2402.17764, 2024.
    [2] Bengio et al., "Estimating or Propagating Gradients Through Stochastic
        Neurons for Conditional Computation", arXiv:1308.3432, 2013 (STE).
"""

import math
from typing import Dict, List, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F

# ── Single source of truth for the 2-bit encoding ──────────────────────
# This constant is used verbatim by export_weights_header() to generate
# the comment block in model_weights.h. Do NOT hand-duplicate this text
# elsewhere — reference this constant instead.
TRIT_ENCODING_SPEC_LINES = [
    "2-BIT PACKED ENCODING (CANONICAL):",
    "  Each ternary weight is stored as 2 bits, 4 trits per byte, LSB-first.",
    "    0b00 = 0   (skip: do not accumulate)",
    "    0b01 = +1  (add:  accumulate +x_i)",
    "    0b10 = -1  (sub:  accumulate -x_i)",
    "    0b11 = reserved (unused, treat as 0)",
    "",
    "  Byte layout: [trit3 : trit2 : trit1 : trit0]",
    "  trit0 occupies bits [1:0], trit3 occupies bits [7:6].",
    "",
    "  To decode trit i from byte b:",
    "    uint8_t code = (b >> (i * 2)) & 0x03;",
    "    int8_t  trit = (code == 0x01) ? +1 : (code == 0x02) ? -1 : 0;",
    "",
    "  This encoding is shared by engine-arduino (C) and engine-fpga (Verilog).",
    "  Any change here MUST be mirrored in both engines.",
]

# ---------------------------------------------------------------------------
# Quantization primitives
# ---------------------------------------------------------------------------

class _TernaryQuantizeSTE(torch.autograd.Function):
    """
    Straight-Through Estimator for ternary quantization.

    Forward:  quantize weights to {-1, 0, +1} via absmean thresholding.
    Backward: pass gradients through unchanged (identity Jacobian).

    This is the standard STE trick from Bengio et al. (2013) — the gradient
    of the quantization step (which is zero almost everywhere and undefined
    at the thresholds) is replaced with the identity, allowing the optimizer
    to update the underlying full-precision latent weights.
    """

    @staticmethod
    def forward(ctx, weight: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        scale = weight.abs().mean()
        threshold = 0.5 * scale

        # Ternary quantization: +1 / 0 / -1
        w_ternary = torch.zeros_like(weight)
        w_ternary[weight > threshold] = 1.0
        w_ternary[weight < -threshold] = -1.0

        # Save scale for the backward pass (not strictly needed for STE,
        # but useful if we later add gradient clipping at the threshold).
        ctx.save_for_backward(weight)

        return w_ternary, scale

    @staticmethod
    def backward(ctx, grad_w_ternary: torch.Tensor, grad_scale: torch.Tensor):
        # STE: ∂L/∂W_latent = ∂L/∂W_ternary  (identity pass-through)
        return grad_w_ternary


def ternary_quantize(weight: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Quantize a weight tensor to {-1, 0, +1} with STE gradient support.

    Args:
        weight: Full-precision weight tensor of any shape.

    Returns:
        w_ternary: Quantized weight tensor (same shape), values in {-1, 0, +1}.
        scale:     Scalar absmean scaling factor (mean of |W|).

    The returned w_ternary supports autograd via STE — gradients flow through
    as if the quantization were the identity function.
    """
    return _TernaryQuantizeSTE.apply(weight)


# ---------------------------------------------------------------------------
# TernaryLinear
# ---------------------------------------------------------------------------

class TernaryLinear(nn.Module):
    """
    Linear layer with ternary weight quantization.

    Drop-in replacement for ``nn.Linear``. Weights are stored in full
    precision (float32) and updated by the optimizer normally. During the
    forward pass, weights are quantized on-the-fly to {-1, 0, +1} via
    absmean thresholding; the backward pass uses STE.

    The output is scaled by the absmean factor so that activation magnitudes
    remain in a sensible range despite the extreme quantization:

        y = (W_q @ x) * scale + bias

    At inference / export time, ``get_ternary_weights()`` returns the frozen
    quantized weights and scale for use by the C / AVR / Verilog engines.

    Args:
        in_features:  Size of each input sample.
        out_features: Size of each output sample.
        bias:         If True (default), adds a learnable bias.
    """

    def __init__(self, in_features: int, out_features: int, bias: bool = True):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features

        # Full-precision latent weights — these are what the optimizer updates.
        self.weight = nn.Parameter(torch.empty(out_features, in_features))

        if bias:
            self.bias = nn.Parameter(torch.zeros(out_features))
        else:
            self.register_parameter("bias", None)

        # Kaiming uniform init — standard for ReLU networks.
        # The fan-in calculation accounts for the weight shape.
        nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        if self.bias is not None:
            fan_in = self.in_features
            bound = 1.0 / math.sqrt(fan_in)
            nn.init.uniform_(self.bias, -bound, bound)

    # ---- forward / quantize ----

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        w_q, scale = ternary_quantize(self.weight)
        out = F.linear(x, w_q) * scale
        if self.bias is not None:
            out = out + self.bias
        return out

    # ---- inference helpers ----

    @torch.no_grad()
    def get_ternary_weights(self) -> Tuple[torch.Tensor, float]:
        """
        Return frozen (no-grad) quantized weights and scale.

        Returns:
            w_q:   int8 tensor with values in {-1, 0, +1}, shape (out, in).
            scale: float, the absmean scaling factor.
        """
        scale = self.weight.abs().mean()
        threshold = 0.5 * scale

        w_q = torch.zeros_like(self.weight, dtype=torch.int8)
        w_q[self.weight > threshold] = 1
        w_q[self.weight < -threshold] = -1

        return w_q, scale.item()

    @torch.no_grad()
    def weight_distribution(self) -> Dict[int, int]:
        """
        Count how many weights fall into each ternary bucket.

        Returns:
            dict mapping {-1: count, 0: count, +1: count}
        """
        w_q, _ = self.get_ternary_weights()
        return {
            -1: int((w_q == -1).sum()),
            0: int((w_q == 0).sum()),
            +1: int((w_q == 1).sum()),
        }

    def extra_repr(self) -> str:
        return (
            f"in_features={self.in_features}, out_features={self.out_features}, "
            f"bias={self.bias is not None}"
        )


# ---------------------------------------------------------------------------
# RMSNorm
# ---------------------------------------------------------------------------

class RMSNorm(nn.Module):
    """
    Root Mean Square Layer Normalization (Zhang & Sennrich, 2019).

    Unlike LayerNorm, RMSNorm does not subtract the mean — it only rescales
    by the root-mean-square of the activations:

        RMSNorm(x) = (x / RMS(x)) * γ
        where RMS(x) = sqrt( mean(x²) + ε )

    This is cheaper to compute (no mean subtraction, no variance) and works
    well with ternary networks because scale-only normalization preserves
    the sign structure that ternary weights exploit.

    Args:
        dim: Feature dimension to normalize over (last axis).
        eps: Small constant for numerical stability.
    """

    def __init__(self, dim: int, eps: float = 1e-8):
        super().__init__()
        self.eps = eps
        self.gamma = nn.Parameter(torch.ones(dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        rms = torch.sqrt(x.pow(2).mean(dim=-1, keepdim=True) + self.eps)
        return (x / rms) * self.gamma

    def extra_repr(self) -> str:
        return f"dim={self.gamma.shape[0]}, eps={self.eps}"


# ---------------------------------------------------------------------------
# TernaryMLP
# ---------------------------------------------------------------------------

class TernaryMLP(nn.Module):
    """
    Complete ternary MLP for intrusion detection.

    Architecture::

        input → [RMSNorm → TernaryLinear → ReLU] × len(hidden_dims) → classifier

    All hidden layers use ternary quantization. The output (classifier) layer
    is ternary by default but can be switched to full-precision ``nn.Linear``
    via ``ternary_output=False`` for more accurate decision boundaries.

    Args:
        input_dim:      Number of input features.
        hidden_dims:    List of hidden layer widths, e.g. [32, 16].
        output_dim:     Number of output classes.
        ternary_output: If True (default), the classifier is TernaryLinear.
        use_rmsnorm:    If True (default), insert RMSNorm before each layer.
    """

    def __init__(
        self,
        input_dim: int,
        hidden_dims: List[int],
        output_dim: int,
        ternary_output: bool = True,
        use_rmsnorm: bool = True,
    ):
        super().__init__()
        self.input_dim = input_dim
        self.hidden_dims = list(hidden_dims)
        self.output_dim = output_dim

        layers: List[nn.Module] = []
        prev_dim = input_dim

        for h_dim in hidden_dims:
            if use_rmsnorm:
                layers.append(RMSNorm(prev_dim))
            layers.append(TernaryLinear(prev_dim, h_dim))
            layers.append(nn.ReLU())
            prev_dim = h_dim

        self.features = nn.Sequential(*layers)

        if ternary_output:
            self.classifier = TernaryLinear(prev_dim, output_dim)
        else:
            self.classifier = nn.Linear(prev_dim, output_dim)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.features(x)
        return self.classifier(x)

    # ---- model analysis helpers ----

    def count_parameters(self) -> Dict[str, int]:
        """
        Count total trainable parameters and ternary-quantized parameters.

        Returns:
            dict with keys 'total' and 'ternary'.
        """
        total = sum(p.numel() for p in self.parameters())
        ternary = sum(
            m.weight.numel()
            for m in self.modules()
            if isinstance(m, TernaryLinear)
        )
        return {"total": total, "ternary": ternary}

    def estimate_packed_size(self) -> Dict[str, int]:
        """
        Estimate the packed model size in bytes for embedded deployment.

        Ternary weights are packed at 2 bits each (4 trits per byte).
        Encoding: 00 = 0, 01 = +1, 10 = -1, 11 = unused.
        This is slightly less dense than the information-theoretic minimum
        of log₂3 ≈ 1.58 bits, but trivial to encode/decode in C and Verilog.

        Biases are stored as int8 on the embedded target (1 byte each).
        Scale factors are float32 (4 bytes each, one per TernaryLinear layer).
        RMSNorm gammas are float32 (4 bytes per feature dimension element).

        Returns:
            dict with detailed byte breakdown and total.
        """
        ternary_weight_count = 0
        bias_count = 0
        scale_count = 0
        rmsnorm_param_count = 0

        for module in self.modules():
            if isinstance(module, TernaryLinear):
                ternary_weight_count += module.weight.numel()
                scale_count += 1
                if module.bias is not None:
                    bias_count += module.bias.numel()
            elif isinstance(module, RMSNorm):
                rmsnorm_param_count += module.gamma.numel()

        packed_weight_bytes = math.ceil(ternary_weight_count * 2 / 8)
        bias_bytes = bias_count  # int8 on embedded
        scale_bytes = scale_count * 4  # float32
        rmsnorm_bytes = rmsnorm_param_count * 4  # float32 gamma

        total = packed_weight_bytes + bias_bytes + scale_bytes + rmsnorm_bytes

        return {
            "ternary_weights": ternary_weight_count,
            "packed_weight_bytes": packed_weight_bytes,
            "bias_bytes": bias_bytes,
            "scale_bytes": scale_bytes,
            "rmsnorm_bytes": rmsnorm_bytes,
            "total_bytes": total,
        }

    def estimate_ram_usage(self, activation_dtype_bytes: int = 2,
                           stack_reserve: int = 128,
                           gamma_in_progmem: bool = True) -> Dict[str, int]:
        """
        Estimate peak runtime RAM usage for embedded inference.

        On the ATmega328P (2048 bytes total RAM), inference needs:
        - **Input buffer**: input_dim × dtype_bytes
        - **Activation buffers**: two ping-pong buffers sized to the largest
          layer dimension (current + next), so we only need max(all dims) × dtype
        - **Scale storage**: one float32 per TernaryLinear layer (always in RAM,
          needed for the multiply after each layer's accumulate loop)
        - **Stack reserve**: function calls, locals, serial buffer

        Weights and biases live in flash via PROGMEM.

        RMSNorm gamma is also placed in PROGMEM by default (gamma_in_progmem=True),
        since it's constant after training and only accessed once per layer.
        Set gamma_in_progmem=False for a conservative estimate where gamma is
        copied to RAM at startup.

        Args:
            activation_dtype_bytes: Bytes per activation element. Default 2
                (int16 fixed-point on AVR, no FPU).
            stack_reserve: Bytes reserved for stack + serial buffer.
            gamma_in_progmem: If True (default), RMSNorm gamma is in PROGMEM
                (read via pgm_read_float), not counted in RAM. Phase 5's C
                code will implement this as const PROGMEM.

        Returns:
            dict with detailed RAM breakdown, total, and headroom vs 2KB.
        """
        all_dims = [self.input_dim] + self.hidden_dims + [self.output_dim]
        max_dim = max(all_dims)

        # Ping-pong buffers: need two buffers of max_dim to hold
        # current-layer input and next-layer output simultaneously
        activation_bytes = 2 * max_dim * activation_dtype_bytes

        # Input buffer (feature vector from UART)
        input_bytes = self.input_dim * activation_dtype_bytes

        # Scale factors kept in RAM (one float32 per TernaryLinear layer)
        num_ternary_layers = sum(
            1 for m in self.modules() if isinstance(m, TernaryLinear)
        )
        scale_bytes = num_ternary_layers * 4

        # RMSNorm gamma: PROGMEM (default) or RAM
        if gamma_in_progmem:
            rmsnorm_ram = 0  # read via pgm_read_float(), no RAM cost
        else:
            rmsnorm_ram = sum(
                m.gamma.numel() * 4
                for m in self.modules() if isinstance(m, RMSNorm)
            )

        total = activation_bytes + input_bytes + scale_bytes + rmsnorm_ram + stack_reserve
        ram_limit = 2048  # ATmega328P

        return {
            "activation_bytes": activation_bytes,
            "input_buffer_bytes": input_bytes,
            "scale_bytes": scale_bytes,
            "rmsnorm_ram_bytes": rmsnorm_ram,
            "gamma_in_progmem": gamma_in_progmem,
            "stack_reserve": stack_reserve,
            "total_bytes": total,
            "ram_limit": ram_limit,
            "headroom_bytes": ram_limit - total,
            "fits": total <= ram_limit,
        }

    def export_weights_header(self, path: str = "model_weights.h") -> str:
        """
        Export trained ternary weights to a C header file for embedded deployment.

        The header includes:
        - The canonical 2-bit encoding spec as a comment block
          (generated from TRIT_ENCODING_SPEC_LINES, not hand-duplicated)
        - Packed weight arrays (4 trits per byte, LSB-first)
        - Bias arrays (int8)
        - Scale factors (float32)
        - RMSNorm gamma arrays (float32)
        - Architecture metadata (#defines for dims)

        This file is the SINGLE shared artifact consumed by:
        - engine-arduino/ (Phase 5): #include "model_weights.h"
        - engine-fpga/    (Phase 6): parsed by a Verilog $readmemh or
                                      converted to .mem by a script

        Args:
            path: Output file path for the generated header.

        Returns:
            The path written to.
        """
        lines = []
        lines.append("/*")
        lines.append(" * model_weights.h — Auto-generated by TernaryMLP.export_weights_header()")
        lines.append(" *")
        lines.append(" * DO NOT EDIT MANUALLY. Re-generate from the trained model checkpoint.")
        lines.append(" *")
        # Emit encoding spec from the single source of truth
        for spec_line in TRIT_ENCODING_SPEC_LINES:
            lines.append(f" * {spec_line}" if spec_line else " *")
        lines.append(" */")
        lines.append("")
        lines.append("#ifndef TERNARYGUARD_MODEL_WEIGHTS_H")
        lines.append("#define TERNARYGUARD_MODEL_WEIGHTS_H")
        lines.append("")
        lines.append("#include <stdint.h>")
        lines.append("#ifdef __AVR__")
        lines.append("#include <avr/pgmspace.h>")
        lines.append("#define TGPROGMEM PROGMEM")
        lines.append("#else")
        lines.append("#define TGPROGMEM")
        lines.append("#endif")
        lines.append("")

        # Architecture defines
        all_dims = [self.input_dim] + self.hidden_dims + [self.output_dim]
        lines.append(f"#define TG_INPUT_DIM  {self.input_dim}")
        lines.append(f"#define TG_OUTPUT_DIM {self.output_dim}")
        lines.append(f"#define TG_NUM_LAYERS {len(all_dims) - 1}")
        dims_str = ", ".join(str(d) for d in all_dims)
        lines.append(f"static const uint8_t TG_DIMS[] = {{{dims_str}}};")
        lines.append("")

        # Export each layer
        layer_idx = 0
        for module in self.modules():
            if isinstance(module, TernaryLinear):
                w_ternary, scale = module.get_ternary_weights()
                w_np = w_ternary.numpy()  # shape: (out_features, in_features)

                # Pack into 2-bit encoding
                packed = self._pack_ternary_2bit(w_np)

                # Write packed weights
                lines.append(f"/* Layer {layer_idx}: {module.in_features} -> {module.out_features} */")
                hex_vals = ", ".join(f"0x{b:02X}" for b in packed)
                lines.append(f"static const uint8_t TGPROGMEM tg_weights_{layer_idx}[] = {{")
                # Wrap at 16 bytes per line for readability
                for i in range(0, len(packed), 16):
                    chunk = packed[i:i+16]
                    hex_line = ", ".join(f"0x{b:02X}" for b in chunk)
                    comma = "," if i + 16 < len(packed) else ""
                    lines.append(f"    {hex_line}{comma}")
                lines.append("};")

                # Bias
                if module.bias is not None:
                    bias_np = module.bias.detach().round().clamp(-128, 127).to(torch.int8).numpy()
                    bias_vals = ", ".join(str(int(b)) for b in bias_np)
                    lines.append(f"static const int8_t TGPROGMEM tg_bias_{layer_idx}[] = {{{bias_vals}}};")

                # Scale
                scale_val = scale.item() if hasattr(scale, 'item') else float(scale)
                lines.append(f"static const float tg_scale_{layer_idx} = {scale_val:.8f}f;")
                lines.append("")
                layer_idx += 1

        # RMSNorm gammas
        norm_idx = 0
        for module in self.modules():
            if isinstance(module, RMSNorm):
                gamma_np = module.gamma.detach().numpy()
                gamma_vals = ", ".join(f"{g:.8f}f" for g in gamma_np)
                lines.append(f"static const float TGPROGMEM tg_rmsnorm_gamma_{norm_idx}[] = {{{gamma_vals}}};")
                norm_idx += 1

        lines.append("")
        lines.append("#endif /* TERNARYGUARD_MODEL_WEIGHTS_H */")
        lines.append("")

        header_content = "\n".join(lines)
        with open(path, 'w') as f:
            f.write(header_content)

        return path

    @staticmethod
    def _pack_ternary_2bit(w: 'np.ndarray') -> List[int]:
        """
        Pack a 2D ternary weight matrix into 2-bit encoded bytes.

        Encoding per TRIT_ENCODING_SPEC_LINES (the single source of truth):
            0b00 = 0, 0b01 = +1, 0b10 = -1

        4 trits per byte, LSB-first: trit0 in bits [1:0], trit3 in bits [7:6].
        Weights are flattened in row-major order.

        Args:
            w: int8 numpy array with values in {-1, 0, +1}.

        Returns:
            List of packed byte values.
        """
        flat = w.flatten()
        packed = []
        for i in range(0, len(flat), 4):
            byte = 0
            for j in range(4):
                if i + j < len(flat):
                    val = int(flat[i + j])
                    if val == 1:
                        code = 0b01
                    elif val == -1:
                        code = 0b10
                    else:
                        code = 0b00
                    byte |= (code << (j * 2))
            packed.append(byte)
        return packed

    def extra_repr(self) -> str:
        return (
            f"input_dim={self.input_dim}, hidden_dims={self.hidden_dims}, "
            f"output_dim={self.output_dim}"
        )
